language: php

php:
  - 7.3

addons:
  chrome: stable

install:
  - cp .env.example .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan dusk:chrome-driver

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - touch database/database.sqlite
  - php artisan serve &
  - chmod -R 0755 vendor/laravel/dusk/bin/

script:
  - vendor/bin/phpunit
  - php artisan dusk
